# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a42xq/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a42xq

PRODUCT_COPY_FILES += \
    vendor/samsung/a42xq/proprietary/vendor/etc/audconf/OPEN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Bluetooth_cal.acdb \
    vendor/samsung/a42xq/proprietary/vendor/etc/audconf/OPEN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/General_cal.acdb \
    vendor/samsung/a42xq/proprietary/vendor/etc/audconf/OPEN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Global_cal.acdb \
    vendor/samsung/a42xq/proprietary/vendor/etc/audconf/OPEN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Handset_cal.acdb \
    vendor/samsung/a42xq/proprietary/vendor/etc/audconf/OPEN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Hdmi_cal.acdb \
    vendor/samsung/a42xq/proprietary/vendor/etc/audconf/OPEN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Headset_cal.acdb \
    vendor/samsung/a42xq/proprietary/vendor/etc/audconf/OPEN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Speaker_cal.acdb \
    vendor/samsung/a42xq/proprietary/vendor/etc/audconf/OPEN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFile.qwsp \
    vendor/samsung/a42xq/proprietary/vendor/etc/qdcm_calib_data_ss_dsi_panel_S6E8FC1_AMS660XR01_HD.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ss_dsi_panel_S6E8FC1_AMS660XR01_HD.xml \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_lsi_s5kgm2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_lsi_s5kgm2.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.13_hynix_hi2021q_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.13_hynix_hi2021q_full.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_hynix_hi2021q.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_hynix_hi2021q.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.2_lsi_s5k4ha.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.2_lsi_s5k4ha.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.3_lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.3_lsi_gc5035.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.sensormodule.4_lsi_gc5035_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.4_lsi_gc5035_macro.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.tuned.hynix_hi2021q.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.hynix_hi2021q.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_gc5035.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_gc5035_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_gc5035_macro.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5k4ha.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5k4ha.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5kgm2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5kgm2.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/f_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/f_dual_calibration.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/ois_mcu_stm32g_fw.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/ois_mcu_stm32g_fw.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/t_tof_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/t_tof_calibration.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/uw_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/uw_dual_calibration.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/w_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/w_dual_calibration.bin \
    vendor/samsung/a42xq/proprietary/vendor/lib64/camera/w_tof_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/w_tof_calibration.bin

PRODUCT_PACKAGES += \
    libIMUSensor \
    libbauthserver \
    libbauthtzcommon \
    libegis_fp_normal_sensor_test \
    libgf_in_system_lib \
    libqfp_sensortest \
    libsec2qc_conversion \
    libsynaFpSensorTestNwd \
    com.samsung.sensor.gc5035 \
    com.samsung.sensor.gc5035_macro \
    com.samsung.sensor.hi2021q \
    com.samsung.sensor.s5k4ha \
    com.samsung.sensor.s5kgm2 \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.depth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.samsung.node.capture_bokeh \
    com.samsung.node.capture_fusion \
    com.samsung.node.multi_frame_video_hdr \
    com.samsung.node.realtimebokeh \
    com.samsung.node.remosaic \
    com.samsung.node.smooth_transition \
    com.samsung.node.uniplugin_capture \
    com.samsung.node.uniplugin_preview \
    com.samsung.node.uniplugin_recording \
    com.samsung.node.uniplugin_vdis \
    com.ss.stats.aec \
    com.ss.stats.af \
    com.ss.stats.awb \
    com.ss.stats.pdlib \
    libMOTION \
    libvdis_interface
